-- Wajbati AI shared database schema for Supabase
create table if not exists public.menu_items (
  id text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  status text not null default 'submitted' check (status in ('submitted','preparing','ready','served')),
  table_no text not null,
  note text,
  total numeric(12,2) not null default 0,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  order_id text not null,
  sold_at timestamptz not null default now(),
  payload jsonb not null
);

create table if not exists public.restaurant_settings (
  id int primary key check (id = 1),
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.restaurant_settings(id,payload)
values (1,'{}'::jsonb)
on conflict (id) do nothing;

create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_sales_sold_at on public.sales(sold_at desc);

-- The browser never talks directly to these tables in production.
-- Keep RLS enabled and use the server-side Service Role key only.
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.sales enable row level security;
alter table public.restaurant_settings enable row level security;
