WajbatiStore.init();
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const httpMode=location.protocol==='http:'||location.protocol==='https:';
let authed=sessionStorage.getItem('wajbati.admin')==='1',adminPin=sessionStorage.getItem('wajbati.admin.pin')||'',remoteReady=false;
let adminMenu=WajbatiStore.getMenu(),adminOrders=WajbatiStore.getOrders(),adminSales=WajbatiStore.getSales(),adminSettings=WajbatiStore.getSettings();
async function api(url,{method='GET',body,admin=true}={}){const r=await fetch(url,{method,headers:{'Content-Type':'application/json',...(admin?{'X-Admin-Pin':adminPin}:{})},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(`HTTP_${r.status}`);return r.json()}
async function loginRemote(pin){if(!httpMode)return pin===WajbatiStore.getPin();try{const j=await api('/api/admin/login',{method:'POST',body:{pin},admin:false});return !!j.ok}catch{return false}}
async function bootstrapIfNeeded(){if(!httpMode||!remoteReady||adminMenu.length)return;try{await api('/api/admin/bootstrap',{method:'POST',body:{menu:WajbatiStore.getMenu(),settings:WajbatiStore.getSettings()}});await loadRemote()}catch{}}
async function loadRemote(){if(!httpMode||!adminPin)return false;try{const [m,o,s,st]=await Promise.all([api('/api/admin/menu'),api('/api/admin/orders'),api('/api/admin/sales'),api('/api/admin/settings')]);adminMenu=m.menu||[];adminOrders=o.orders||[];adminSales=s.sales||[];adminSettings=st.settings||{};remoteReady=true;return true}catch{remoteReady=false;return false}}
async function show(){if(!authed)return;$('#login').classList.add('hidden');$('#adminApp').classList.remove('hidden');if(await loadRemote()){await bootstrapIfNeeded();await loadRemote()}renderAllLocal()}
if(authed&&adminPin)show();
$('#loginBtn').onclick=async()=>{const pin=$('#pin').value.trim();$('#loginMsg').innerHTML='<div class="notice">جاري التحقق...</div>';if(await loginRemote(pin)){authed=true;adminPin=pin;sessionStorage.setItem('wajbati.admin','1');sessionStorage.setItem('wajbati.admin.pin',pin);$('#loginMsg').innerHTML='';show()}else $('#loginMsg').innerHTML='<div class="notice">الرمز غير صحيح أو الخادم غير متصل.</div>'};
$('#logout').onclick=()=>{sessionStorage.removeItem('wajbati.admin');sessionStorage.removeItem('wajbati.admin.pin');location.reload()};
WajbatiStore.categories.forEach(c=>$('#category').insertAdjacentHTML('beforeend',`<option value="${c.id}">${c.name}</option>`));document.querySelectorAll('.admin-side button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-side button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active');renderAll()});
const sn=s=>({submitted:'تم الاستلام',preparing:'قيد التحضير',ready:'جاهز',served:'تم التسليم'}[s]||s),next=s=>({submitted:'preparing',preparing:'ready',ready:'served'}[s]);
function renderOrders(){const os=adminOrders.filter(o=>o.status!=='served');$('#ordersList').innerHTML=os.length?os.map(o=>`<article class="card order-card"><div><b>${o.id}</b><small>طاولة ${esc(o.table)}</small></div><div><b>${o.items.map(i=>`${i.qty}× ${esc(i.name)}`).join('، ')}</b><small>${WajbatiStore.money(o.total)} د.أ</small>${o.note?`<div class="kitchen-note"><span>📝 ملاحظة الزبون</span><strong>${esc(o.note)}</strong></div>`:''}</div><span class="status-pill ${o.status}">${sn(o.status)}</span><div>${next(o.status)?`<button class="primary advance" data-id="${o.id}" data-status="${next(o.status)}">${sn(next(o.status))}</button>`:''}</div></article>`).join(''):'<div class="notice">لا توجد طلبات نشطة.</div>';document.querySelectorAll('.advance').forEach(b=>b.onclick=()=>advanceOrder(b.dataset.id,b.dataset.status))}
async function advanceOrder(id,status){if(remoteReady){try{const j=await api(`/api/admin/orders/${encodeURIComponent(id)}/status`,{method:'PATCH',body:{status}});adminOrders=adminOrders.map(o=>o.id===id?j.order:o);await loadRemote();renderAllLocal();return}catch{}}WajbatiStore.updateOrderStatus(id,status);adminOrders=WajbatiStore.getOrders();adminSales=WajbatiStore.getSales();renderAllLocal()}
function renderMenu(){const m=adminMenu;$('#adminMenu').innerHTML=m.map(x=>`<div class="dish-admin"><img src="${x.image}"><div><b>${esc(x.name)}</b><small>${WajbatiStore.categoryName(x.category)} • ${WajbatiStore.money(x.price)} د.أ</small></div><span>${x.available?'متاح':'موقوف'}</span><button class="ghost toggle" data-id="${x.id}">${x.available?'إيقاف':'تفعيل'}</button><div><button class="ghost edit" data-id="${x.id}">تعديل</button> <button class="primary danger del" data-id="${x.id}">حذف</button></div></div>`).join('');document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>toggleDish(b.dataset.id));document.querySelectorAll('.del').forEach(b=>b.onclick=()=>deleteDish(b.dataset.id));document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>edit(b.dataset.id))}
async function saveDish(item){if(remoteReady){try{await api('/api/admin/menu/'+encodeURIComponent(item.id),{method:'PUT',body:item});adminMenu=adminMenu.some(x=>x.id===item.id)?adminMenu.map(x=>x.id===item.id?item:x):[...adminMenu,item];return true}catch{}}const m=WajbatiStore.getMenu(),i=m.findIndex(x=>x.id===item.id);i>=0?m[i]=item:m.push(item);WajbatiStore.saveMenu(m);adminMenu=m;return false}
async function toggleDish(id){const x=adminMenu.find(i=>i.id===id);if(!x)return;await saveDish({...x,available:!x.available});renderMenu()}
async function deleteDish(id){if(!confirm('حذف الصنف؟'))return;if(remoteReady){try{await api('/api/admin/menu/'+encodeURIComponent(id),{method:'DELETE'});adminMenu=adminMenu.filter(x=>x.id!==id);renderMenu();return}catch{}}WajbatiStore.saveMenu(WajbatiStore.getMenu().filter(x=>x.id!==id));adminMenu=WajbatiStore.getMenu();renderMenu()}
const fields=['name','englishName','category','price','calories','protein','carbs','fat','aliases','description','ingredients','cookingMethod','servingStyle','taste','spiceLevel','prepTime','allergens','customization','pairing'];function edit(id){const x=adminMenu.find(i=>i.id===id);if(!x)return;$('#editId').value=id;fields.forEach(k=>{const e=$('#'+k);if(e)e.value=k==='allergens'?(x[k]||[]).join('، '):(x[k]??'')});$('#imageData').value=x.image||'';window.scrollTo({top:0,behavior:'smooth'});$('#cancelEdit').classList.remove('hidden')}function reset(){$('#dishForm').reset();$('#editId').value='';$('#imageData').value='';$('#cancelEdit').classList.add('hidden')}$('#cancelEdit').onclick=reset;$('#image').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>2500000){alert('الصورة كبيرة. استخدم صورة أقل من 2.5MB.');e.target.value='';return}const r=new FileReader();r.onload=()=>$('#imageData').value=r.result;r.readAsDataURL(f)};
$('#dishForm').onsubmit=async e=>{e.preventDefault();const id=$('#editId').value||('u'+Date.now()),old=adminMenu.find(x=>x.id===id),obj={id,name:$('#name').value.trim(),englishName:$('#englishName').value.trim(),aliases:$('#aliases').value.trim(),category:$('#category').value,price:Number($('#price').value),calories:Number($('#calories').value)||0,protein:Number($('#protein').value)||0,carbs:Number($('#carbs').value)||0,fat:Number($('#fat').value)||0,description:$('#description').value.trim(),ingredients:$('#ingredients').value.trim(),cookingMethod:$('#cookingMethod').value.trim(),servingStyle:$('#servingStyle').value.trim(),taste:$('#taste').value.trim(),spiceLevel:$('#spiceLevel').value.trim(),prepTime:$('#prepTime').value.trim(),customization:$('#customization').value.trim(),pairing:$('#pairing').value.trim(),allergens:$('#allergens').value.split(/[،,]/).map(s=>s.trim()).filter(Boolean),available:old?.available??true,image:$('#imageData').value||old?.image||'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'};const existed=!!old;await saveDish(obj);$('#menuNotice').innerHTML=`<div class="notice">تمت ${existed?'تحديث':'إضافة'} <b>${esc(obj.name)}</b> بنجاح، والمستشار صار يعرفه فورًا.</div>`;reset();renderMenu()};
function history(){const sales=adminSales,orders=adminOrders,now=new Date(),day=now.toISOString().slice(0,10),month=now.toISOString().slice(0,7),ds=sales.filter(x=>x.soldAt?.slice(0,10)===day),ms=sales.filter(x=>x.soldAt?.slice(0,7)===month);$('#todayRevenue').textContent=WajbatiStore.money(ds.reduce((s,x)=>s+Number(x.total||0),0))+' د.أ';$('#todayOrders').textContent=orders.filter(x=>x.createdAt?.slice(0,10)===day).length;$('#monthRevenue').textContent=WajbatiStore.money(ms.reduce((s,x)=>s+Number(x.total||0),0))+' د.أ';$('#monthItems').textContent=ms.reduce((s,x)=>s+Number(x.qty||0),0);const map={};ms.forEach(x=>{map[x.name]??={name:x.name,category:x.category,qty:0,total:0};map[x.name].qty+=Number(x.qty||0);map[x.name].total+=Number(x.total||0)});$('#inventoryBody').innerHTML=Object.values(map).map(x=>`<tr><td>${esc(x.name)}</td><td>${WajbatiStore.categoryName(x.category)}</td><td>${x.qty}</td><td>${WajbatiStore.money(x.total)}</td></tr>`).join('')||'<tr><td colspan="4">لا توجد مبيعات هذا الشهر.</td></tr>'}
$('#exportCsv').onclick=()=>{const month=new Date().toISOString().slice(0,7),rows=[['الصنف','القسم','الكمية','الإيراد'],...adminSales.filter(x=>x.soldAt?.startsWith(month)).map(x=>[x.name,WajbatiStore.categoryName(x.category),x.qty,x.total])],csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`wajbati-${month}.csv`;a.click()};
const settingsMap={restaurantName:'restaurantName',restaurantPhone:'phone',restaurantHours:'hours',restaurantAddress:'address',restaurantPayment:'payment',restaurantWifi:'wifi',restaurantReservations:'reservations',restaurantDelivery:'delivery',restaurantParking:'parking',restaurantHalal:'halal',restaurantPolicies:'policies',restaurantKnowledgeBase:'knowledgeBase'};function renderSettings(){Object.entries(settingsMap).forEach(([id,k])=>$('#'+id).value=adminSettings[k]||'')}$('#saveRestaurantSettings').onclick=async()=>{const s={...adminSettings};Object.entries(settingsMap).forEach(([id,k])=>s[k]=$('#'+id).value.trim());if(remoteReady){try{const j=await api('/api/admin/settings',{method:'PUT',body:s});adminSettings=j.settings||s;$('#restaurantSettingsNotice').innerHTML='<div class="notice">تم الحفظ على قاعدة البيانات، والمستشار يقرأ المعلومات فورًا.</div>';return}catch{}}WajbatiStore.setSettings(s);adminSettings=s;$('#restaurantSettingsNotice').innerHTML='<div class="notice">تم الحفظ محليًا.</div>'};
$('#savePin').onclick=()=>{if(remoteReady){$('#pinNotice').innerHTML='<div class="notice">رمز الأدمن في النسخة المنشورة يُدار من متغير ADMIN_PIN في الاستضافة.</div>';return}const p=$('#newPin').value.trim();if(p.length<4)return $('#pinNotice').innerHTML='<div class="notice">استخدم 4 أحرف/أرقام على الأقل.</div>';WajbatiStore.setPin(p);$('#pinNotice').innerHTML='<div class="notice">تم تغيير الرمز.</div>'};
function renderAllLocal(){renderOrders();renderMenu();history();renderSettings()}
async function renderAll(){if(await loadRemote())renderAllLocal();else{adminMenu=WajbatiStore.getMenu();adminOrders=WajbatiStore.getOrders();adminSales=WajbatiStore.getSales();adminSettings=WajbatiStore.getSettings();renderAllLocal()}}
window.addEventListener('storage',()=>{if(!remoteReady)renderAll()});setInterval(()=>authed&&renderAll(),2500);
