WajbatiStore.init();
const API='https://ywfajrnwyixficsjujfl.supabase.co/functions/v1/wajbati-api';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let authed=sessionStorage.getItem('wajbati.admin')==='1',adminPin=sessionStorage.getItem('wajbati.admin.pin')||'';
let adminMenu=[],adminOrders=[],adminSales=[],adminSettings={};
async function request(url,opts={}){const r=await fetch(url,opts);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP_${r.status}`);return j}
async function apiGet(action,params={}){const u=new URL(API);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));return request(u.toString())}
async function apiPost(action,data={},pin=adminPin){return request(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,pin,...data})})}
async function loginRemote(pin){try{return !!(await apiPost('admin_login',{pin},'')).ok}catch{return false}}
async function loadRemote(){if(!adminPin)return false;try{const [m,o,s,st]=await Promise.all([apiGet('menu'),apiPost('admin_orders'),apiPost('sales'),apiGet('settings')]);adminMenu=m.items||[];adminOrders=o.orders||[];adminSales=s.sales||[];adminSettings=st.settings||{};WajbatiStore.saveMenu(adminMenu);WajbatiStore.setSettings(adminSettings);return true}catch{return false}}
async function show(){if(!authed)return;$('#login').classList.add('hidden');$('#adminApp').classList.remove('hidden');await loadRemote();renderAllLocal()}
if(authed&&adminPin)show();
$('#loginBtn').onclick=async()=>{const pin=$('#pin').value.trim();$('#loginMsg').innerHTML='<div class="notice">جاري التحقق...</div>';if(await loginRemote(pin)){authed=true;adminPin=pin;sessionStorage.setItem('wajbati.admin','1');sessionStorage.setItem('wajbati.admin.pin',pin);$('#loginMsg').innerHTML='';show()}else $('#loginMsg').innerHTML='<div class="notice">الرمز غير صحيح.</div>'};
$('#logout').onclick=()=>{sessionStorage.removeItem('wajbati.admin');sessionStorage.removeItem('wajbati.admin.pin');location.reload()};
WajbatiStore.categories.forEach(c=>$('#category').insertAdjacentHTML('beforeend',`<option value="${c.id}">${c.name}</option>`));
document.querySelectorAll('.admin-side button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-side button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active');renderAllLocal()});
const sn=s=>({submitted:'تم الاستلام',preparing:'قيد التحضير',ready:'جاهز',served:'تم التسليم'}[s]||s),next=s=>({submitted:'preparing',preparing:'ready',ready:'served'}[s]);
function renderOrders(){const os=adminOrders.filter(o=>o.status!=='served');$('#ordersList').innerHTML=os.length?os.map(o=>`<article class="card order-card"><div><b>${esc(o.id)}</b><small>طاولة ${esc(o.table)}</small></div><div><b>${(o.items||[]).map(i=>`${i.qty}× ${esc(i.name)}`).join('، ')}</b><small>${WajbatiStore.money(o.total)} د.أ</small>${o.note?`<div class="kitchen-note"><span>📝 ملاحظة الزبون</span><strong>${esc(o.note)}</strong></div>`:''}</div><span class="status-pill ${o.status}">${sn(o.status)}</span><div>${next(o.status)?`<button class="primary advance" data-id="${o.id}" data-status="${next(o.status)}">${sn(next(o.status))}</button>`:''}</div></article>`).join(''):'<div class="notice">لا توجد طلبات نشطة.</div>';document.querySelectorAll('.advance').forEach(b=>b.onclick=()=>advanceOrder(b.dataset.id,b.dataset.status))}
async function advanceOrder(id,status){try{await apiPost('update_order_status',{id,status});await loadRemote();renderAllLocal()}catch{alert('تعذّر تحديث حالة الطلب')}}
function renderMenu(){$('#adminMenu').innerHTML=adminMenu.map(x=>`<div class="dish-admin"><img src="${x.image}"><div><b>${esc(x.name)}</b><small>${WajbatiStore.categoryName(x.category)} • ${WajbatiStore.money(x.price)} د.أ</small></div><span>${x.available?'متاح':'موقوف'}</span><button class="ghost toggle" data-id="${x.id}">${x.available?'إيقاف':'تفعيل'}</button><div><button class="ghost edit" data-id="${x.id}">تعديل</button> <button class="primary danger del" data-id="${x.id}">حذف</button></div></div>`).join('');document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>toggleDish(b.dataset.id));document.querySelectorAll('.del').forEach(b=>b.onclick=()=>deleteDish(b.dataset.id));document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>edit(b.dataset.id))}
async function persistMenu(){await apiPost('save_menu',{items:adminMenu});WajbatiStore.saveMenu(adminMenu)}
async function toggleDish(id){const x=adminMenu.find(i=>i.id===id);if(!x)return;x.available=!x.available;try{await persistMenu();renderMenu()}catch{x.available=!x.available;alert('تعذّر حفظ التغيير')}}
async function deleteDish(id){if(!confirm('حذف الصنف؟'))return;const old=[...adminMenu];adminMenu=adminMenu.filter(x=>x.id!==id);try{await persistMenu();renderMenu()}catch{adminMenu=old;alert('تعذّر حذف الصنف')}}
const fields=['name','englishName','category','price','calories','protein','carbs','fat','aliases','description','ingredients','cookingMethod','servingStyle','taste','spiceLevel','prepTime','allergens','customization','pairing'];
function edit(id){const x=adminMenu.find(i=>i.id===id);if(!x)return;$('#editId').value=id;fields.forEach(k=>{const e=$('#'+k);if(e)e.value=k==='allergens'?(x[k]||[]).join('، '):(x[k]??'')});$('#imageData').value=x.image||'';window.scrollTo({top:0,behavior:'smooth'});$('#cancelEdit').classList.remove('hidden')}
function reset(){$('#dishForm').reset();$('#editId').value='';$('#imageData').value='';$('#cancelEdit').classList.add('hidden')}
$('#cancelEdit').onclick=reset;
$('#image').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>2500000){alert('الصورة كبيرة. استخدم صورة أقل من 2.5MB.');e.target.value='';return}const r=new FileReader();r.onload=()=>$('#imageData').value=r.result;r.readAsDataURL(f)};
$('#dishForm').onsubmit=async e=>{e.preventDefault();const id=$('#editId').value||('u'+Date.now()),old=adminMenu.find(x=>x.id===id),obj={id,name:$('#name').value.trim(),englishName:$('#englishName').value.trim(),aliases:$('#aliases').value.trim(),category:$('#category').value,price:Number($('#price').value),calories:Number($('#calories').value)||0,protein:Number($('#protein').value)||0,carbs:Number($('#carbs').value)||0,fat:Number($('#fat').value)||0,description:$('#description').value.trim(),ingredients:$('#ingredients').value.trim(),cookingMethod:$('#cookingMethod').value.trim(),servingStyle:$('#servingStyle').value.trim(),taste:$('#taste').value.trim(),spiceLevel:$('#spiceLevel').value.trim(),prepTime:$('#prepTime').value.trim(),customization:$('#customization').value.trim(),pairing:$('#pairing').value.trim(),allergens:$('#allergens').value.split(/[،,]/).map(s=>s.trim()).filter(Boolean),available:old?.available??true,image:$('#imageData').value||old?.image||'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'};const existed=!!old,i=adminMenu.findIndex(x=>x.id===id);i>=0?adminMenu[i]=obj:adminMenu.push(obj);try{await persistMenu();$('#menuNotice').innerHTML=`<div class="notice">تمت ${existed?'تحديث':'إضافة'} <b>${esc(obj.name)}</b> بنجاح، والمستشار صار يعرفه فورًا.</div>`;reset();renderMenu()}catch{$('#menuNotice').innerHTML='<div class="notice">تعذّر حفظ الصنف.</div>'}};
function history(){const sales=adminSales,orders=adminOrders,now=new Date(),day=now.toISOString().slice(0,10),month=now.toISOString().slice(0,7),ds=sales.filter(x=>x.soldAt?.slice(0,10)===day),ms=sales.filter(x=>x.soldAt?.slice(0,7)===month);$('#todayRevenue').textContent=WajbatiStore.money(ds.reduce((s,x)=>s+Number(x.total||0),0))+' د.أ';$('#todayOrders').textContent=orders.filter(x=>x.createdAt?.slice(0,10)===day&&x.status!=='cancelled').length;$('#monthRevenue').textContent=WajbatiStore.money(ms.reduce((s,x)=>s+Number(x.total||0),0))+' د.أ';$('#monthItems').textContent=ms.reduce((s,x)=>s+Number(x.qty||0),0);const map={};ms.forEach(x=>{map[x.name]??={name:x.name,category:x.category,qty:0,total:0};map[x.name].qty+=Number(x.qty||0);map[x.name].total+=Number(x.total||0)});$('#inventoryBody').innerHTML=Object.values(map).map(x=>`<tr><td>${esc(x.name)}</td><td>${WajbatiStore.categoryName(x.category)}</td><td>${x.qty}</td><td>${WajbatiStore.money(x.total)}</td></tr>`).join('')||'<tr><td colspan="4">لا توجد مبيعات هذا الشهر.</td></tr>'}
$('#exportCsv').onclick=()=>{const month=new Date().toISOString().slice(0,7),rows=[['الصنف','القسم','الكمية','الإيراد'],...adminSales.filter(x=>x.soldAt?.startsWith(month)).map(x=>[x.name,WajbatiStore.categoryName(x.category),x.qty,x.total])],csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`wajbati-${month}.csv`;a.click()};
const settingsMap={restaurantName:'restaurantName',restaurantPhone:'phone',restaurantHours:'hours',restaurantAddress:'address',restaurantPayment:'payment',restaurantWifi:'wifi',restaurantReservations:'reservations',restaurantDelivery:'delivery',restaurantParking:'parking',restaurantHalal:'halal',restaurantPolicies:'policies',restaurantKnowledgeBase:'knowledgeBase'};
function renderSettings(){Object.entries(settingsMap).forEach(([id,k])=>$('#'+id).value=adminSettings[k]||'')}
$('#saveRestaurantSettings').onclick=async()=>{const s={...adminSettings};Object.entries(settingsMap).forEach(([id,k])=>s[k]=$('#'+id).value.trim());try{await apiPost('save_settings',{settings:s});adminSettings=s;WajbatiStore.setSettings(s);$('#restaurantSettingsNotice').innerHTML='<div class="notice">تم الحفظ، والمستشار يقرأ المعلومات فورًا.</div>'}catch{$('#restaurantSettingsNotice').innerHTML='<div class="notice">تعذّر الحفظ.</div>'}};
$('#savePin').onclick=async()=>{const p=$('#newPin').value.trim();if(p.length<4)return $('#pinNotice').innerHTML='<div class="notice">استخدم 4 أحرف/أرقام على الأقل.</div>';try{await apiPost('change_pin',{newPin:p});adminPin=p;sessionStorage.setItem('wajbati.admin.pin',p);$('#newPin').value='';$('#pinNotice').innerHTML='<div class="notice">تم تغيير الرمز بنجاح.</div>'}catch{$('#pinNotice').innerHTML='<div class="notice">تعذّر تغيير الرمز.</div>'}};
function renderAllLocal(){renderOrders();renderMenu();history();renderSettings()}
async function refresh(){if(!authed)return;if(await loadRemote())renderAllLocal()}
setInterval(refresh,2500);

/* WAJBATI_ADMIN_CANCEL_V10 */
renderOrders=function(){
  const active=adminOrders.filter(o=>o.status!=='served'&&o.status!=='cancelled'),cancelled=adminOrders.filter(o=>o.status==='cancelled');
  const statusName=s=>({submitted:'تم الاستلام',preparing:'قيد التحضير',ready:'جاهز',served:'تم التسليم',cancelled:'ملغي'}[s]||s),nextStatus=s=>({submitted:'preparing',preparing:'ready',ready:'served'}[s]);
  const activeHtml=active.length?active.map(o=>`<article class="card order-card"><div><b>${esc(o.id)}</b><small>طاولة ${esc(o.table)}</small></div><div><b>${(o.items||[]).map(i=>`${i.qty}× ${esc(i.name)}`).join('، ')}</b><small>${WajbatiStore.money(o.total)} د.أ</small>${o.note?`<div class="kitchen-note"><span>📝 ملاحظة الزبون</span><strong>${esc(o.note)}</strong></div>`:''}</div><span class="status-pill ${o.status}">${statusName(o.status)}</span><div>${nextStatus(o.status)?`<button class="primary advance" data-id="${o.id}" data-status="${nextStatus(o.status)}">${statusName(nextStatus(o.status))}</button>`:''}</div></article>`).join(''):'<div class="notice">لا توجد طلبات نشطة.</div>';
  const cancelledHtml=`<div class="orders-section-head cancelled-head"><h2>الطلبات الملغية</h2><span>${cancelled.length}</span></div>`+(cancelled.length?cancelled.map(o=>`<article class="card order-card cancelled-order"><div><b>${esc(o.id)}</b><small>طاولة ${esc(o.table)}</small></div><div><b>${(o.items||[]).map(i=>`${i.qty}× ${esc(i.name)}`).join('، ')}</b><small>${WajbatiStore.money(o.total)} د.أ · لا يُحتسب بالمبيعات</small><div class="cancel-admin-note"><span>سبب الإلغاء</span><strong>${esc(o.cancellationReason||'لم يُذكر سبب')}</strong>${o.cancelledAt?`<small>${new Date(o.cancelledAt).toLocaleString('ar-JO')}</small>`:''}</div></div><span class="status-pill cancelled">ملغي</span><div></div></article>`).join(''):'<div class="notice subtle">لا توجد طلبات ملغية.</div>');
  $('#ordersList').innerHTML=activeHtml+cancelledHtml;document.querySelectorAll('.advance').forEach(b=>b.onclick=()=>advanceOrder(b.dataset.id,b.dataset.status));
};
