WajbatiStore.init();
let cart=[],profile={goal:'balance',avoid:''},currentOrderId=sessionStorage.getItem('wajbati.currentOrder')||'';
let liveMenu=WajbatiStore.getMenu(),liveSettings=WajbatiStore.getSettings(),remoteReady=false,trackingBusy=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const httpMode=location.protocol==='http:'||location.protocol==='https:';
async function getJson(url,opts){const r=await fetch(url,opts);if(!r.ok)throw new Error(`HTTP_${r.status}`);return r.json()}
async function refreshRemote(){if(!httpMode)return false;try{const [m,s]=await Promise.all([getJson('/api/menu'),getJson('/api/settings')]);if(Array.isArray(m.menu)&&m.menu.length)liveMenu=m.menu;if(s.settings)liveSettings=s.settings;remoteReady=true;return true}catch{remoteReady=false;return false}}
function currentMenu(){return liveMenu.filter(x=>x.available)}
function renderMenu(){const menu=currentMenu();$('#menuSections').innerHTML=WajbatiStore.categories.map(c=>{const xs=menu.filter(x=>x.category===c.id);if(!xs.length)return'';return`<section class="category"><h2>${c.icon} ${c.name}</h2><div class="menu-grid">${xs.map(x=>`<article class="card dish"><img src="${x.image}" alt="${esc(x.name)}"><div class="dish-body"><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="meta"><span>${x.calories||0} kcal</span><span>بروتين ${x.protein||0}g</span><span>كرب ${x.carbs||0}g</span></div><footer><b>${WajbatiStore.money(x.price)} د.أ</b><button class="primary add" data-id="${x.id}">أضف</button></footer></div></article>`).join('')}</div></section>`}).join('');document.querySelectorAll('.add').forEach(b=>b.onclick=()=>addToCart(b.dataset.id))}
function addToCart(id){const x=liveMenu.find(i=>i.id===id);if(!x)return;const e=cart.find(i=>i.id===id);e?e.qty++:cart.push({...x,qty:1});renderCart();$('#cart').scrollIntoView({behavior:'smooth',block:'center'});$('#orderResult').innerHTML=`<div class="notice">تمت إضافة <b>${esc(x.name)}</b> إلى طلبك ✓</div>`}
function renderCart(){$('#cartList').innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><span>${esc(x.name)}</span><span class="qty"><button data-a="minus" data-id="${x.id}">−</button>${x.qty}<button data-a="plus" data-id="${x.id}">+</button></span><b>${WajbatiStore.money(x.price*x.qty)}</b></div>`).join(''):'<p class="muted">لم تضف أصنافًا بعد.</p>';$('#cartTotal').textContent=WajbatiStore.money(cart.reduce((s,x)=>s+x.price*x.qty,0));document.querySelectorAll('.qty button').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.id);b.dataset.a==='plus'?x.qty++:x.qty--;cart=cart.filter(i=>i.qty>0);renderCart()})}
function msg(t,type){const d=document.createElement('div');d.className='msg '+type;d.textContent=t;$('#messages').appendChild(d);$('#messages').scrollTop=$('#messages').scrollHeight}
const history=[];async function ask(m){if(httpMode){try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),8000);const r=await fetch('/api/ai-chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({message:m,profile,history:history.slice(-12),menu:currentMenu(),settings:liveSettings})});clearTimeout(timer);if(r.ok){const j=await r.json();if(j.text)return j.text}}catch{}}return WajbatiAgent(m,{...profile,menu:liveMenu,settings:liveSettings})}
$('#chatForm').onsubmit=async e=>{e.preventDefault();const m=$('#chatInput').value.trim();if(!m)return;msg(m,'user');$('#chatInput').value='';const b=$('#chatForm button');b.disabled=true;b.textContent='...';try{const a=await ask(m);msg(a,'ai');history.push({role:'user',text:m},{role:'assistant',text:a})}catch{msg(WajbatiAgent(m,profile),'ai')}finally{b.disabled=false;b.textContent='إرسال'}};
const goalText={balance:'سأوازن بين السعرات والبروتين والكربوهيدرات.',muscle:'سأعطي أولوية للأعلى بروتين.',cut:'سأفضّل الخيارات الأخف بالسعرات.',keto:'سأعطي أولوية للأقل كربوهيدرات.'};function setGoal(g,announce=true){profile.goal=g;document.querySelectorAll('.goal').forEach(b=>b.classList.toggle('active',b.dataset.goal===g));$('#goalFeedback').textContent=goalText[g];if(announce)msg(`تمام، فعّلت هدف ${document.querySelector(`.goal[data-goal="${g}"] b`).textContent}. اسألني الآن وبحسبه لك على الهدف.`,'ai');setTimeout(()=>{document.querySelector('.chat').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#chatInput').focus(),500)},70)}document.querySelectorAll('.goal').forEach(b=>b.onclick=()=>setGoal(b.dataset.goal));$('#avoid').onchange=e=>profile.avoid=e.target.value;setGoal('balance',false);
const statusNames={submitted:'تم استلام الطلب',preparing:'قيد التحضير',ready:'جاهز',served:'تم التسليم'},friendly={submitted:['🌿','صحة وعافية مقدمًا!','استلمنا طلبك بنجاح، وهلّق بنرتبه للمطبخ.'],preparing:['👨‍🍳','ما رح نطوّل عليك','الشيف شغّال على طلبك الآن.'],ready:['😋','طلبك صار جاهز','باقي يوصل لعند طاولتك.'],served:['❤️','صحة وهنا!','نتمنى تكون وجبتك على مزاجك.']},flow=['submitted','preparing','ready','served'];
function paintTracking(o){const a=$('#customerTracking');if(!o){a.innerHTML='';return}const i=flow.indexOf(o.status),f=friendly[o.status]||['🍽️','طلبك معنا','تابع حالته من هنا'];a.innerHTML=`<div class="customer-tracking-card"><div class="customer-tracking-head"><div><small>تتبع الطلب</small><h3>${statusNames[o.status]||o.status}</h3><p>طلب ${o.id} · طاولة ${esc(o.table)}</p></div><span class="status-pill ${o.status}">${statusNames[o.status]||o.status}</span></div><div class="status-friendly-message"><span>${f[0]}</span><div><b>${f[1]}</b><p>${f[2]}</p></div></div>${o.note?`<div class="customer-order-note">📝 ${esc(o.note)}</div>`:''}<div class="customer-steps">${flow.map((s,n)=>`<div class="customer-step ${n<i?'done':n===i?'current':''}"><span>${n<i?'✓':n+1}</span><b>${statusNames[s]}</b></div>`).join('')}</div></div>`}
async function tracking(){if(!currentOrderId){paintTracking(null);return}if(trackingBusy)return;trackingBusy=true;try{if(httpMode){const j=await getJson('/api/orders/'+encodeURIComponent(currentOrderId));paintTracking(j.order);return}}catch{}finally{trackingBusy=false}const o=WajbatiStore.getOrders().find(x=>x.id===currentOrderId);paintTracking(o)}
async function submitOrder(table,note){const total=cart.reduce((s,x)=>s+x.price*x.qty,0);if(httpMode){try{const j=await getJson('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,note,items:cart,total})});return j.order}catch{}}return WajbatiStore.submitOrder(table,cart,note)}
$('#submitOrder').onclick=async()=>{const table=$('#tableNo').value.trim(),note=$('#chefNote').value.trim();if(!table)return $('#orderResult').innerHTML='<div class="notice">أدخل رقم الطاولة أولًا.</div>';if(!cart.length)return $('#orderResult').innerHTML='<div class="notice">أضف صنفًا واحدًا على الأقل.</div>';const btn=$('#submitOrder');btn.disabled=true;btn.textContent='جاري الإرسال...';try{const o=await submitOrder(table,note);currentOrderId=o.id;sessionStorage.setItem('wajbati.currentOrder',o.id);cart=[];renderCart();$('#chefNote').value='';$('#noteCount').textContent='0/220';$('#orderResult').innerHTML=`<div class="notice">تم إرسال الطلب <b>${o.id}</b> للمطبخ. تقدر تتابع حالته تحت.</div>`;paintTracking(o);setTimeout(()=>$('#customerTracking').scrollIntoView({behavior:'smooth',block:'center'}),100)}finally{btn.disabled=false;btn.textContent='إرسال الطلب للمطبخ'}};
$('#chefNote').oninput=e=>$('#noteCount').textContent=`${e.target.value.length}/220`;document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth',block:b.dataset.scroll==='cart'?'center':'start'})});
window.addEventListener('storage',e=>{if(!remoteReady&&e.key===WajbatiStore.KEYS.menu){liveMenu=WajbatiStore.getMenu();renderMenu()}if(!remoteReady&&e.key===WajbatiStore.KEYS.orders)tracking()});
(async()=>{await refreshRemote();renderMenu();renderCart();tracking();setInterval(tracking,1800);setInterval(async()=>{if(await refreshRemote())renderMenu()},12000)})();
