WajbatiStore.init();
const API='https://ywfajrnwyixficsjujfl.supabase.co/functions/v1/wajbati-api';
let cart=[],profile={goal:'balance',avoid:''},currentOrderId=sessionStorage.getItem('wajbati.currentOrder')||'';
let liveMenu=WajbatiStore.getMenu(),liveSettings=WajbatiStore.getSettings(),trackingBusy=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
async function getJson(url,opts={}){const r=await fetch(url,opts);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP_${r.status}`);return j}
async function apiGet(action,params={}){const u=new URL(API);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));return getJson(u.toString())}
async function apiPost(action,data={}){return getJson(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})})}
async function refreshRemote(){try{const [m,s]=await Promise.all([apiGet('menu'),apiGet('settings')]);if(Array.isArray(m.items)&&m.items.length){liveMenu=m.items;WajbatiStore.saveMenu(liveMenu)}if(s.settings){liveSettings=s.settings;WajbatiStore.setSettings(liveSettings)}return true}catch{return false}}
function currentMenu(){return liveMenu.filter(x=>x.available)}
function renderMenu(){const menu=currentMenu();$('#menuSections').innerHTML=WajbatiStore.categories.map(c=>{const xs=menu.filter(x=>x.category===c.id);if(!xs.length)return'';return`<section class="category"><h2>${c.icon} ${c.name}</h2><div class="menu-grid">${xs.map(x=>`<article class="card dish"><img src="${x.image}" alt="${esc(x.name)}"><div class="dish-body"><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="meta"><span>${x.calories||0} kcal</span><span>بروتين ${x.protein||0}g</span><span>كرب ${x.carbs||0}g</span></div><footer><b>${WajbatiStore.money(x.price)} د.أ</b><button class="primary add" data-id="${x.id}">أضف</button></footer></div></article>`).join('')}</div></section>`}).join('');document.querySelectorAll('.add').forEach(b=>b.onclick=()=>addToCart(b.dataset.id))}
function addToCart(id){const x=liveMenu.find(i=>i.id===id);if(!x)return;const e=cart.find(i=>i.id===id);e?e.qty++:cart.push({...x,qty:1});renderCart();$('#cart').scrollIntoView({behavior:'smooth',block:'center'});$('#orderResult').innerHTML=`<div class="notice">تمت إضافة <b>${esc(x.name)}</b> إلى طلبك ✓</div>`}
function renderCart(){$('#cartList').innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><span>${esc(x.name)}</span><span class="qty"><button data-a="minus" data-id="${x.id}">−</button>${x.qty}<button data-a="plus" data-id="${x.id}">+</button></span><b>${WajbatiStore.money(x.price*x.qty)}</b></div>`).join(''):'<p class="muted">لم تضف أصنافًا بعد.</p>';$('#cartTotal').textContent=WajbatiStore.money(cart.reduce((s,x)=>s+x.price*x.qty,0));document.querySelectorAll('.qty button').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.id);if(!x)return;b.dataset.a==='plus'?x.qty++:x.qty--;cart=cart.filter(i=>i.qty>0);renderCart()})}
function msg(t,type){const d=document.createElement('div');d.className='msg '+type;d.textContent=t;$('#messages').appendChild(d);$('#messages').scrollTop=$('#messages').scrollHeight}
const history=[];async function ask(m){return WajbatiAgent(m,profile)}
$('#chatForm').onsubmit=async e=>{e.preventDefault();const m=$('#chatInput').value.trim();if(!m)return;msg(m,'user');$('#chatInput').value='';const b=$('#chatForm button');b.disabled=true;b.textContent='...';try{const a=await ask(m);msg(a,'ai');history.push({role:'user',text:m},{role:'assistant',text:a})}catch{msg('صار خطأ بسيط. جرّب سؤالك مرة ثانية.','ai')}finally{b.disabled=false;b.textContent='إرسال'}};
const goalText={balance:'سأوازن بين السعرات والبروتين والكربوهيدرات.',muscle:'سأعطي أولوية للأعلى بروتين.',cut:'سأفضّل الخيارات الأخف بالسعرات.',keto:'سأعطي أولوية للأقل كربوهيدرات.'};
function setGoal(g,announce=true){profile.goal=g;document.querySelectorAll('.goal').forEach(b=>b.classList.toggle('active',b.dataset.goal===g));$('#goalFeedback').textContent=goalText[g];if(announce)msg(`تمام، فعّلت هدف ${document.querySelector(`.goal[data-goal="${g}"] b`).textContent}. اسألني الآن وبحسبه لك على الهدف.`,'ai');setTimeout(()=>{document.querySelector('.chat').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#chatInput').focus(),450)},60)}
document.querySelectorAll('.goal').forEach(b=>b.onclick=()=>setGoal(b.dataset.goal));$('#avoid').onchange=e=>profile.avoid=e.target.value;setGoal('balance',false);
const statusNames={submitted:'تم استلام الطلب',preparing:'قيد التحضير',ready:'جاهز',served:'تم التسليم'},friendly={submitted:['🌿','صحة وعافية مقدمًا!','استلمنا طلبك بنجاح، وهلّق بنرتبه للمطبخ.'],preparing:['👨‍🍳','ما رح نطوّل عليك','الشيف شغّال على طلبك الآن.'],ready:['😋','طلبك صار جاهز','باقي يوصل لعند طاولتك.'],served:['❤️','صحة وهنا!','نتمنى تكون وجبتك على مزاجك.']},flow=['submitted','preparing','ready','served'];
function paintTracking(o){const a=$('#customerTracking');if(!o){a.innerHTML='';return}const i=flow.indexOf(o.status),f=friendly[o.status]||['🍽️','طلبك معنا','تابع حالته من هنا'];a.innerHTML=`<div class="customer-tracking-card"><div class="customer-tracking-head"><div><small>تتبع الطلب</small><h3>${statusNames[o.status]||o.status}</h3><p>طلب ${o.id} · طاولة ${esc(o.table)}</p></div><span class="status-pill ${o.status}">${statusNames[o.status]||o.status}</span></div><div class="status-friendly-message"><span>${f[0]}</span><div><b>${f[1]}</b><p>${f[2]}</p></div></div>${o.note?`<div class="customer-order-note">📝 ${esc(o.note)}</div>`:''}<div class="customer-steps">${flow.map((s,n)=>`<div class="customer-step ${n<i?'done':n===i?'current':''}"><span>${n<i?'✓':n+1}</span><b>${statusNames[s]}</b></div>`).join('')}</div></div>`}
async function tracking(){if(!currentOrderId){paintTracking(null);return}if(trackingBusy)return;trackingBusy=true;try{const j=await apiGet('order',{id:currentOrderId});paintTracking(j.order)}catch{}finally{trackingBusy=false}}
async function submitOrder(table,note){const items=cart.map(x=>({id:x.id,name:x.name,category:x.category,qty:x.qty,price:x.price})),total=items.reduce((s,x)=>s+x.price*x.qty,0);const j=await apiPost('create_order',{order:{table,note,items,total}});return j.order}
$('#submitOrder').onclick=async()=>{const table=$('#tableNo').value.trim(),note=$('#chefNote').value.trim();if(!table)return $('#orderResult').innerHTML='<div class="notice">أدخل رقم الطاولة أولًا.</div>';if(!cart.length)return $('#orderResult').innerHTML='<div class="notice">أضف صنفًا واحدًا على الأقل.</div>';const btn=$('#submitOrder');btn.disabled=true;btn.textContent='جاري الإرسال...';try{const o=await submitOrder(table,note);currentOrderId=o.id;sessionStorage.setItem('wajbati.currentOrder',o.id);cart=[];renderCart();$('#chefNote').value='';$('#noteCount').textContent='0/220';$('#orderResult').innerHTML=`<div class="notice">تم إرسال الطلب <b>${o.id}</b> للمطبخ. تقدر تتابع حالته تحت.</div>`;paintTracking(o);setTimeout(()=>$('#customerTracking').scrollIntoView({behavior:'smooth',block:'center'}),100)}catch{$('#orderResult').innerHTML='<div class="notice">تعذّر إرسال الطلب. جرّب مرة ثانية.</div>'}finally{btn.disabled=false;btn.textContent='إرسال الطلب للمطبخ'}};
$('#chefNote').oninput=e=>$('#noteCount').textContent=`${e.target.value.length}/220`;
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth',block:b.dataset.scroll==='cart'?'center':'start'})});
(async()=>{await refreshRemote();renderMenu();renderCart();tracking();setInterval(tracking,1800);setInterval(async()=>{if(await refreshRemote())renderMenu()},10000)})();