const http=require('http'),fs=require('fs'),path=require('path');
const PORT=Number(process.env.PORT||4173),HOST=process.env.HOST||'0.0.0.0',ROOT=__dirname;
let calorieDB=[];for(let i=1;i<=6;i++){try{calorieDB.push(...JSON.parse(fs.readFileSync(path.join(ROOT,'data',`calories-${i}.json`),'utf8')))}catch{}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.jpg':'image/jpeg','.png':'image/png'};
const norm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9\u0600-\u06ff\s]/g,' ').replace(/\s+/g,' ').trim();
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type.startsWith('application/json')?JSON.stringify(body):body)}
function body(req){return new Promise((ok,bad)=>{let d='';req.on('data',c=>{d+=c;if(d.length>2e6){bad(new Error('too large'));req.destroy()}});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){bad(e)}});req.on('error',bad)})}
function calorieContext(message){const q=norm(message),tokens=q.split(' ').filter(x=>x.length>2);return calorieDB.map(x=>{const n=norm(x.food);let score=0;tokens.forEach(t=>{if(n.includes(t)||t.includes(n))score++});if(q.includes(n)&&n.length>2)score+=5;return{x,score}}).filter(r=>r.score>0).sort((a,b)=>b.score-a.score).slice(0,8).map(r=>r.x)}
async function aiChat(req,res){try{const data=await body(req),key=process.env.OPENAI_API_KEY;if(!key)return send(res,503,{offline:true,error:'AI key not configured'});const menu=Array.isArray(data.menu)?data.menu:[],settings=data.settings||{},history=Array.isArray(data.history)?data.history.slice(-12):[],cals=calorieContext(data.message);const system=`You are Wajbati, a restaurant concierge and nutrition assistant. Answer in the user's language and style: Modern Standard Arabic, Jordanian/Levantine colloquial Arabic, or English. Answer every restaurant-related question you reasonably can. Be natural and useful, not robotic. Ground restaurant-specific claims ONLY in CURRENT_MENU and RESTAURANT_SETTINGS. Never invent unavailable restaurant facts. If the user asks for a category such as drinks, desserts, appetizers, salads, or mains, list ALL currently available items in that category. You can answer ingredients, cooking method, serving style, taste, spice level, preparation time, customization, pairings, prices, calories, macros, allergens, dietary goals, comparisons, restaurant policies, hours, payment, Wi-Fi, reservations, delivery, parking, and order-related questions when context contains the answer. For nutrition facts outside the menu, use CALORIE_REFERENCE when it matches. Keep allergy advice cautious and tell severe-allergy users to confirm with staff.\nRESTAURANT_SETTINGS=${JSON.stringify(settings)}\nCURRENT_MENU=${JSON.stringify(menu)}\nCALORIE_REFERENCE=${JSON.stringify(cals)}\nPROFILE=${JSON.stringify(data.profile||{})}\nRECENT_HISTORY=${JSON.stringify(history)}`;const payload={model:process.env.OPENAI_MODEL||'gpt-5-mini',input:[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content:[{type:'input_text',text:String(data.message||'').slice(0,1800)}]}],max_output_tokens:900};const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)return send(res,502,{error:j?.error?.message||`AI HTTP ${r.status}`});const text=(j.output||[]).flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n').trim();return send(res,200,{text})}catch(e){return send(res,500,{error:e.message})}}
function staticFile(req,res){let p=decodeURIComponent(req.url.split('?')[0]);if(p==='/')p='/index.html';if(p==='/admin')p='/admin.html';const f=path.normalize(path.join(ROOT,p));if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory())return send(res,404,'Not found','text/plain; charset=utf-8');res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname==='/api/health')return send(res,200,{ok:true,calorieRecords:calorieDB.length});if(u.pathname==='/api/ai-chat'&&req.method==='POST')return aiChat(req,res);return staticFile(req,res)}).listen(PORT,HOST,()=>console.log(`Wajbati AI V8 running on http://localhost:${PORT} | admin: /admin | calorie records: ${calorieDB.length}`));
