const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||4173),HOST=process.env.HOST||'0.0.0.0',ROOT=__dirname;
const SUPABASE_URL=(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY||'';
const ADMIN_PIN=String(process.env.ADMIN_PIN||'2468');
const dbEnabled=Boolean(SUPABASE_URL&&SUPABASE_KEY);
let calorieDB=[];for(let i=1;i<=6;i++){try{calorieDB.push(...JSON.parse(fs.readFileSync(path.join(ROOT,'data',`calories-${i}.json`),'utf8')))}catch{}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp'};
const norm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9\u0600-\u06ff\s]/g,' ').replace(/\s+/g,' ').trim();
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type.startsWith('application/json')?JSON.stringify(body):body)}
function body(req){return new Promise((ok,bad)=>{let d='';req.on('data',c=>{d+=c;if(d.length>4e6){bad(new Error('too large'));req.destroy()}});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){bad(e)}});req.on('error',bad)})}
function adminOk(req){return crypto.timingSafeEqual(Buffer.from(String(req.headers['x-admin-pin']||'').padEnd(64).slice(0,64)),Buffer.from(ADMIN_PIN.padEnd(64).slice(0,64)))}
async function sb(resource,{method='GET',query='',data,prefer}={}){if(!dbEnabled)throw new Error('SUPABASE_NOT_CONFIGURED');const r=await fetch(`${SUPABASE_URL}/rest/v1/${resource}${query?`?${query}`:''}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:data===undefined?undefined:JSON.stringify(data)});const text=await r.text();if(!r.ok)throw new Error(`SUPABASE_${r.status}:${text.slice(0,600)}`);if(!text)return null;try{return JSON.parse(text)}catch{return text}}
async function getMenu(){const rows=await sb('menu_items',{query:'select=payload&order=updated_at.asc'});return (rows||[]).map(r=>r.payload)}
async function getSettings(){const rows=await sb('restaurant_settings',{query:'id=eq.1&select=payload'});return rows?.[0]?.payload||{}}
async function getOrder(id){const rows=await sb('orders',{query:`id=eq.${encodeURIComponent(id)}&select=payload`});return rows?.[0]?.payload||null}
function calorieContext(message){const q=norm(message),tokens=q.split(' ').filter(x=>x.length>2);return calorieDB.map(x=>{const n=norm(x.food);let score=0;tokens.forEach(t=>{if(n.includes(t)||t.includes(n))score++});if(q.includes(n)&&n.length>2)score+=5;return{x,score}}).filter(r=>r.score>0).sort((a,b)=>b.score-a.score).slice(0,8).map(r=>r.x)}
async function aiChat(req,res){try{const data=await body(req),key=process.env.OPENAI_API_KEY;if(!key)return send(res,503,{offline:true,error:'AI key not configured'});let menu=Array.isArray(data.menu)?data.menu:[],settings=data.settings||{};if(dbEnabled){try{[menu,settings]=await Promise.all([getMenu(),getSettings()])}catch{}}const history=Array.isArray(data.history)?data.history.slice(-12):[],cals=calorieContext(data.message);const system=`You are Wajbati, a restaurant concierge and nutrition assistant. Answer in the user's language and style: Modern Standard Arabic, Jordanian/Levantine colloquial Arabic, or English. Answer every restaurant-related question you reasonably can. Be natural and useful, not robotic. Ground restaurant-specific claims ONLY in CURRENT_MENU and RESTAURANT_SETTINGS. Never invent unavailable restaurant facts. If the user asks for a category such as drinks, desserts, appetizers, salads, or mains, list ALL currently available items in that category. You can answer ingredients, cooking method, serving style, taste, spice level, preparation time, customization, pairings, prices, calories, macros, allergens, dietary goals, comparisons, restaurant policies, hours, payment, Wi-Fi, reservations, delivery, parking, and order-related questions when context contains the answer. For nutrition facts outside the menu, use CALORIE_REFERENCE when it matches. Keep allergy advice cautious and tell severe-allergy users to confirm with staff.\nRESTAURANT_SETTINGS=${JSON.stringify(settings)}\nCURRENT_MENU=${JSON.stringify(menu)}\nCALORIE_REFERENCE=${JSON.stringify(cals)}\nPROFILE=${JSON.stringify(data.profile||{})}\nRECENT_HISTORY=${JSON.stringify(history)}`;const payload={model:process.env.OPENAI_MODEL||'gpt-5-mini',input:[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content:[{type:'input_text',text:String(data.message||'').slice(0,1800)}]}],max_output_tokens:900};const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)return send(res,502,{error:j?.error?.message||`AI HTTP ${r.status}`});const text=(j.output||[]).flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n').trim();return send(res,200,{text})}catch(e){return send(res,500,{error:e.message})}}
function orderId(){return `W-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}
async function api(req,res,u){try{
  if(u.pathname==='/api/health')return send(res,200,{ok:true,database:dbEnabled?'supabase':'local-fallback',calorieRecords:calorieDB.length});
  if(u.pathname==='/api/ai-chat'&&req.method==='POST')return aiChat(req,res);
  if(u.pathname==='/api/menu'&&req.method==='GET')return send(res,200,{menu:await getMenu()});
  if(u.pathname==='/api/settings'&&req.method==='GET')return send(res,200,{settings:await getSettings()});
  if(u.pathname==='/api/orders'&&req.method==='POST'){const d=await body(req),items=Array.isArray(d.items)?d.items:[];if(!String(d.table||'').trim()||!items.length)return send(res,400,{error:'TABLE_AND_ITEMS_REQUIRED'});const id=orderId(),createdAt=new Date().toISOString(),total=Number(d.total)||items.reduce((s,x)=>s+(Number(x.price)||0)*(Number(x.qty)||1),0),order={id,table:String(d.table).trim(),note:String(d.note||'').slice(0,220),items,total,status:'submitted',createdAt,updatedAt:createdAt};await sb('orders',{method:'POST',data:{id,status:'submitted',table_no:order.table,note:order.note,total,created_at:createdAt,updated_at:createdAt,payload:order},prefer:'return=minimal'});return send(res,201,{order})}
  if(u.pathname.startsWith('/api/orders/')&&req.method==='GET'){const id=decodeURIComponent(u.pathname.split('/').pop()),order=await getOrder(id);return order?send(res,200,{order}):send(res,404,{error:'NOT_FOUND'})}
  if(u.pathname==='/api/admin/login'&&req.method==='POST'){const d=await body(req);return send(res,String(d.pin||'')===ADMIN_PIN?200:401,{ok:String(d.pin||'')===ADMIN_PIN})}
  if(u.pathname.startsWith('/api/admin/')){if(!adminOk(req))return send(res,401,{error:'UNAUTHORIZED'});
    if(u.pathname==='/api/admin/bootstrap'&&req.method==='POST'){const d=await body(req),existing=await getMenu();if(!existing.length&&Array.isArray(d.menu)&&d.menu.length){await sb('menu_items',{method:'POST',data:d.menu.map(x=>({id:x.id,payload:x})),prefer:'resolution=merge-duplicates,return=minimal'})}if(d.settings){await sb('restaurant_settings',{method:'POST',data:{id:1,payload:d.settings},prefer:'resolution=merge-duplicates,return=minimal'})}return send(res,200,{ok:true})}
    if(u.pathname==='/api/admin/orders'&&req.method==='GET'){const rows=await sb('orders',{query:'select=payload&order=created_at.desc&limit=500'});return send(res,200,{orders:(rows||[]).map(r=>r.payload)})}
    if(/^\/api\/admin\/orders\/[^/]+\/status$/.test(u.pathname)&&req.method==='PATCH'){const id=decodeURIComponent(u.pathname.split('/')[4]),d=await body(req),status=String(d.status||''),allowed=['submitted','preparing','ready','served'];if(!allowed.includes(status))return send(res,400,{error:'BAD_STATUS'});const order=await getOrder(id);if(!order)return send(res,404,{error:'NOT_FOUND'});order.status=status;order.updatedAt=new Date().toISOString();await sb('orders',{method:'PATCH',query:`id=eq.${encodeURIComponent(id)}`,data:{status,updated_at:order.updatedAt,payload:order},prefer:'return=minimal'});if(status==='served'&&!order.salesRecorded){const soldAt=new Date().toISOString(),sales=(order.items||[]).map(x=>({order_id:id,sold_at:soldAt,payload:{orderId:id,itemId:x.id||'',name:x.name,category:x.category,qty:Number(x.qty)||1,total:(Number(x.price)||0)*(Number(x.qty)||1),soldAt}}));if(sales.length)await sb('sales',{method:'POST',data:sales,prefer:'return=minimal'});order.salesRecorded=true;await sb('orders',{method:'PATCH',query:`id=eq.${encodeURIComponent(id)}`,data:{payload:order},prefer:'return=minimal'})}return send(res,200,{order})}
    if(u.pathname==='/api/admin/menu'&&req.method==='GET')return send(res,200,{menu:await getMenu()});
    if(u.pathname.startsWith('/api/admin/menu/')&&req.method==='PUT'){const id=decodeURIComponent(u.pathname.split('/').pop()),d=await body(req),item={...d,id};await sb('menu_items',{method:'POST',data:{id,payload:item,updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=minimal'});return send(res,200,{item})}
    if(u.pathname.startsWith('/api/admin/menu/')&&req.method==='DELETE'){const id=decodeURIComponent(u.pathname.split('/').pop());await sb('menu_items',{method:'DELETE',query:`id=eq.${encodeURIComponent(id)}`});return send(res,200,{ok:true})}
    if(u.pathname==='/api/admin/settings'&&req.method==='GET')return send(res,200,{settings:await getSettings()});
    if(u.pathname==='/api/admin/settings'&&req.method==='PUT'){const d=await body(req);await sb('restaurant_settings',{method:'POST',data:{id:1,payload:d},prefer:'resolution=merge-duplicates,return=minimal'});return send(res,200,{settings:d})}
    if(u.pathname==='/api/admin/sales'&&req.method==='GET'){const month=u.searchParams.get('month')||new Date().toISOString().slice(0,7),start=`${month}-01T00:00:00.000Z`,end=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),1)).toISOString(),rows=await sb('sales',{query:`sold_at=gte.${encodeURIComponent(start)}&sold_at=lt.${encodeURIComponent(end)}&select=payload&order=sold_at.desc`});return send(res,200,{sales:(rows||[]).map(r=>r.payload)})}
  }
  return false;
}catch(e){if(e.message==='SUPABASE_NOT_CONFIGURED')return send(res,503,{error:'SUPABASE_NOT_CONFIGURED'});return send(res,500,{error:e.message})}}
function staticFile(req,res){let p=decodeURIComponent(req.url.split('?')[0]);if(p==='/')p='/index.html';if(p==='/admin'||p==='/admin/')p='/admin.html';const f=path.normalize(path.join(ROOT,p));if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory())return send(res,404,'Not found','text/plain; charset=utf-8');res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream','Cache-Control':'no-cache'});fs.createReadStream(f).pipe(res)}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/')){const handled=await api(req,res,u);if(handled!==false)return}return staticFile(req,res)}).listen(PORT,HOST,()=>console.log(`Wajbati AI running on http://localhost:${PORT} | admin: /admin | database: ${dbEnabled?'Supabase':'not configured'}`));
