const WajbatiStore=(()=>{
  const KEYS={menu:'wajbati.v8.menu',orders:'wajbati.v8.orders',sales:'wajbati.v8.sales',settings:'wajbati.v8.settings',pin:'wajbati.v8.pin'};
  const categories=[{id:'main',name:'الأطباق الرئيسية',icon:'🍽️'},{id:'drinks',name:'المشروبات',icon:'🥤'},{id:'appetizers',name:'المقبلات',icon:'🥙'},{id:'salads',name:'السلطات',icon:'🥗'},{id:'desserts',name:'الحلويات',icon:'🍰'}];
  const img={chicken:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=82',shawarma:'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=82',salmon:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=82',pasta:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=82',lemon:'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=82',orange:'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=900&q=82',hummus:'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=900&q=82',mutabbal:'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=900&q=82',salad:'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=900&q=82',fattoush:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=82',cake:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=82',kunafa:'https://images.unsplash.com/photo-1579888944880-d98341245702?auto=format&fit=crop&w=900&q=82'};
  const defaults=[
    {id:'chicken',name:'وعاء الدجاج المتوازن',englishName:'Balanced Chicken Bowl',aliases:'دجاج، chicken bowl',category:'main',price:7.25,calories:610,protein:48,carbs:62,fat:18,description:'دجاج مشوي مع أرز وخضار طازجة وصوص أعشاب خفيف.',ingredients:'صدر دجاج، أرز، ذرة، خس، خيار، طماطم، صوص أعشاب',cookingMethod:'يُتبل صدر الدجاج ثم يُشوى على الجريل حتى ينضج، ويُقدّم فوق الأرز والخضار.',servingStyle:'يُقدّم في وعاء مع الأرز والخضار والصوص على الجنب أو فوق الطبق حسب الطلب.',taste:'خفيف ومتوازن بنكهة أعشاب وشواء',spiceLevel:'غير حار',prepTime:'12-15 دقيقة',customization:'بدون صوص، بدون بصل، تقليل الأرز، زيادة خضار',pairing:'يناسب معه ليمون بالنعناع أو فتوش',allergens:['حليب'],image:img.chicken,available:true},
    {id:'shawarma',name:'شاورما دجاج',englishName:'Chicken Shawarma',aliases:'شاورما، shawarma، shawerma',category:'main',price:5.5,calories:590,protein:36,carbs:58,fat:23,description:'شاورما دجاج متبلة تقدم مع خبز وصوص ثوم وخضار.',ingredients:'دجاج متبل، خبز عربي، ثوم، مخلل، طماطم، بهارات',cookingMethod:'يُتبل الدجاج بتتبيلة الشاورما ثم يُطهى بحرارة عالية ويُقطع شرائح رفيعة.',servingStyle:'تُقدّم كسندويش أو طبق، مع الثوم والمخلل حسب الرغبة.',taste:'متبلة ومالحة قليلًا مع نكهة ثوم',spiceLevel:'غير حار افتراضيًا ويمكن إضافة الحار',prepTime:'8-12 دقيقة',customization:'بدون ثوم، بدون مخلل، بدون بصل، زيادة دجاج',pairing:'يناسب معها بطاطا أو ليمون بالنعناع',allergens:['غلوتين'],image:img.shawarma,available:true},
    {id:'salmon',name:'سلمون مشوي',englishName:'Grilled Salmon',aliases:'سالمون، salmon',category:'main',price:12.5,calories:540,protein:46,carbs:22,fat:28,description:'فيليه سلمون مشوي مع خضار موسمية.',ingredients:'سلمون، ليمون، زيت زيتون، خضار، أعشاب',cookingMethod:'يُشوى السلمون على الجريل حتى يصل إلى درجة النضج المناسبة مع أعشاب وليمون.',servingStyle:'يُقدّم ساخنًا مع خضار مشوية وشرائح ليمون.',taste:'غني وخفيف الحموضة',spiceLevel:'غير حار',prepTime:'15-18 دقيقة',customization:'بدون زيت إضافي، زيادة خضار',pairing:'يناسب معه فتوش أو عصير برتقال',allergens:['سمك'],image:img.salmon,available:true},
    {id:'pasta',name:'باستا خضار',englishName:'Vegetable Pasta',aliases:'باستا، pasta',category:'main',price:6.25,calories:680,protein:21,carbs:91,fat:24,description:'باستا مع خضار وصوص طماطم بالأعشاب.',ingredients:'باستا، طماطم، فلفل، فطر، كوسا، أعشاب',cookingMethod:'تُسلق الباستا ثم تُقلب مع الخضار وصوص الطماطم.',servingStyle:'تُقدّم ساخنة في طبق عميق مع أعشاب طازجة.',taste:'طماطم وأعشاب بطعم خفيف',spiceLevel:'غير حار',prepTime:'12-15 دقيقة',customization:'بدون فطر، بدون جبنة، زيادة خضار',pairing:'يناسب معها سلطة سيزر أو مشروب بارد',allergens:['غلوتين'],image:img.pasta,available:true},
    {id:'lemon',name:'ليمون بالنعناع',englishName:'Mint Lemonade',aliases:'ليمون نعنع، lemonade، mint lemonade',category:'drinks',price:2.25,calories:95,protein:1,carbs:24,fat:0,description:'ليمون طازج مع نعناع وثلج.',ingredients:'ليمون، نعناع، ماء، ثلج، سكر حسب الوصفة',cookingMethod:'يُخلط الليمون والنعناع مع الثلج ويُحضّر طازجًا عند الطلب.',servingStyle:'يُقدّم باردًا مع الثلج وورق نعناع.',taste:'حامض ومنعش',spiceLevel:'غير حار',prepTime:'3-5 دقائق',customization:'بدون سكر أو سكر أقل',pairing:'مناسب مع الشاورما والأطباق المشوية',allergens:[],image:img.lemon,available:true},
    {id:'orange',name:'عصير برتقال طازج',englishName:'Fresh Orange Juice',aliases:'برتقال، orange juice',category:'drinks',price:2.5,calories:110,protein:2,carbs:26,fat:0,description:'عصير برتقال طبيعي طازج.',ingredients:'برتقال طازج',cookingMethod:'يُعصر البرتقال عند الطلب.',servingStyle:'يُقدّم باردًا.',taste:'حلو وحامض طبيعيًا',spiceLevel:'غير حار',prepTime:'3-5 دقائق',customization:'بدون ثلج',pairing:'يناسب الإفطار والسلطات',allergens:[],image:img.orange,available:true},
    {id:'hummus',name:'حمص',englishName:'Hummus',aliases:'حمص، hummus',category:'appetizers',price:3.25,calories:360,protein:12,carbs:34,fat:20,description:'حمص كريمي مع طحينية وزيت زيتون.',ingredients:'حمص، طحينية، ليمون، زيت زيتون، ثوم',cookingMethod:'يُخلط الحمص المسلوق مع الطحينية والليمون حتى يصبح كريميًا.',servingStyle:'يُقدّم بدرجة باردة أو معتدلة مع زيت زيتون وخبز.',taste:'كريمي وحامض خفيف',spiceLevel:'غير حار',prepTime:'5 دقائق',customization:'بدون ثوم، زيت أقل',pairing:'يناسب المشاوي والشاورما',allergens:['سمسم'],image:img.hummus,available:true},
    {id:'mutabbal',name:'متبل',englishName:'Mutabbal',aliases:'متبل، moutabal، mutabbal',category:'appetizers',price:3.5,calories:300,protein:8,carbs:22,fat:21,description:'باذنجان مشوي مع طحينية وليمون.',ingredients:'باذنجان، طحينية، ليمون، ثوم، زيت زيتون',cookingMethod:'يُشوى الباذنجان ثم يُهرس ويُخلط مع الطحينية والليمون.',servingStyle:'يُقدّم باردًا مع زيت زيتون وخبز.',taste:'مدخن وكريمي',spiceLevel:'غير حار',prepTime:'5 دقائق',customization:'بدون ثوم، زيت أقل',pairing:'يناسب الأطباق المشوية',allergens:['سمسم'],image:img.mutabbal,available:true},
    {id:'caesar',name:'سلطة سيزر',englishName:'Caesar Salad',aliases:'سيزر، caesar',category:'salads',price:4.75,calories:390,protein:13,carbs:28,fat:25,description:'خس روماني مع كروتون وصوص سيزر.',ingredients:'خس، كروتون، جبنة، صوص سيزر',cookingMethod:'تُجهز طازجة عند الطلب دون طبخ.',servingStyle:'تُقدّم باردة.',taste:'كريمي ومالح خفيف',spiceLevel:'غير حار',prepTime:'5-7 دقائق',customization:'بدون كروتون، الصوص على الجنب',pairing:'مناسبة مع السلمون أو الباستا',allergens:['حليب','غلوتين','بيض'],image:img.salad,available:true},
    {id:'fattoush',name:'فتوش',englishName:'Fattoush',aliases:'فتوش، fattoush',category:'salads',price:3.5,calories:260,protein:6,carbs:35,fat:11,description:'خضار طازجة مع سماق وخبز محمص.',ingredients:'خس، خيار، طماطم، فجل، سماق، خبز',cookingMethod:'تُقطع الخضار طازجة ويُضاف الخبز المحمص والتتبيلة قبل التقديم.',servingStyle:'يُقدّم باردًا وطازجًا.',taste:'حامض ومنعش مع سماق',spiceLevel:'غير حار',prepTime:'5-7 دقائق',customization:'بدون خبز، بدون بصل',pairing:'مناسب مع المشاوي',allergens:['غلوتين'],image:img.fattoush,available:true},
    {id:'cheesecake',name:'تشيز كيك',englishName:'Cheesecake',aliases:'تشيز كيك، cheesecake',category:'desserts',price:3.75,calories:460,protein:7,carbs:48,fat:27,description:'قطعة تشيز كيك ناعمة تقدم باردة.',ingredients:'جبنة كريمية، بسكويت، سكر، زبدة، بيض',cookingMethod:'تُحضّر وتُخبز ثم تُبرد قبل التقديم.',servingStyle:'تُقدّم باردة كقطعة فردية.',taste:'كريمي وحلو',spiceLevel:'غير حار',prepTime:'جاهزة للتقديم خلال 2-3 دقائق',customization:'يمكن طلب الصوص على الجنب حسب التوفر',pairing:'مناسبة مع القهوة',allergens:['حليب','غلوتين','بيض'],image:img.cake,available:true},
    {id:'kunafa',name:'كنافة',englishName:'Kunafa',aliases:'كنافة، knafeh، kunafa',category:'desserts',price:3.25,calories:510,protein:11,carbs:63,fat:24,description:'كنافة ساخنة بالجبنة والقطر.',ingredients:'شعيرية كنافة، جبنة، سمن، قطر، فستق حسب التوفر',cookingMethod:'تُخبز حتى تتحمر ثم يُضاف القطر.',servingStyle:'تُقدّم ساخنة.',taste:'حلوة وغنية',spiceLevel:'غير حار',prepTime:'5-8 دقائق',customization:'قطر أقل حسب الطلب',pairing:'مناسبة مع القهوة أو الشاي',allergens:['حليب','غلوتين','مكسرات'],image:img.kunafa,available:true}
  ];
  const defaultSettings={restaurantName:'Wajbati',phone:'',hours:'',address:'',payment:'كاش، Visa، Mastercard',wifi:'',reservations:'',delivery:'',parking:'',halal:'جميع اللحوم المستخدمة حلال',policies:'',knowledgeBase:'',currency:'د.أ'};
  const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}; const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  function init(){if(!localStorage.getItem(KEYS.menu))write(KEYS.menu,defaults);if(!localStorage.getItem(KEYS.orders))write(KEYS.orders,[]);if(!localStorage.getItem(KEYS.sales))write(KEYS.sales,[]);if(!localStorage.getItem(KEYS.settings))write(KEYS.settings,defaultSettings);if(!localStorage.getItem(KEYS.pin))localStorage.setItem(KEYS.pin,'2468')}
  function submitOrder(table,cart,note=''){const orders=read(KEYS.orders,[]),o={id:'#'+String(Date.now()).slice(-6),table,status:'submitted',note,createdAt:new Date().toISOString(),items:cart.map(x=>({id:x.id,name:x.name,category:x.category,qty:x.qty,price:x.price})),total:cart.reduce((s,x)=>s+x.price*x.qty,0)};orders.unshift(o);write(KEYS.orders,orders);return o}
  function updateOrderStatus(id,status){const os=read(KEYS.orders,[]),o=os.find(x=>x.id===id);if(!o)return;if(o.status!=='served'&&status==='served'){const sales=read(KEYS.sales,[]);o.items.forEach(i=>sales.push({name:i.name,category:i.category,qty:i.qty,total:i.price*i.qty,soldAt:new Date().toISOString()}));write(KEYS.sales,sales)}o.status=status;o.updatedAt=new Date().toISOString();write(KEYS.orders,os)}
  return{KEYS,categories,init,getMenu:()=>read(KEYS.menu,defaults),saveMenu:v=>write(KEYS.menu,v),getOrders:()=>read(KEYS.orders,[]),getSales:()=>read(KEYS.sales,[]),submitOrder,updateOrderStatus,getSettings:()=>read(KEYS.settings,defaultSettings),setSettings:v=>write(KEYS.settings,v),getPin:()=>localStorage.getItem(KEYS.pin)||'2468',setPin:p=>localStorage.setItem(KEYS.pin,p),money:n=>Number(n||0).toFixed(2),categoryName:id=>categories.find(c=>c.id===id)?.name||'غير مصنف'}
})();

const WajbatiAgent=(()=>{
  let lastItemId='';
  const arNorm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/[^\u0600-\u06ff\w\s.]/g,' ').replace(/\s+/g,' ').trim();
  const isEnglish=s=>(String(s).match(/[A-Za-z]/g)||[]).length>(String(s).match(/[\u0600-\u06ff]/g)||[]).length;
  const has=(q,words)=>words.some(w=>q.includes(arNorm(w)));
  const list=(xs,en)=>xs.map(x=>en?`• ${x.englishName||x.name} — ${WajbatiStore.money(x.price)} JOD, ${x.calories} kcal`:`• ${x.name} — ${WajbatiStore.money(x.price)} د.أ، ${x.calories} سعرة`).join('\n');
  function itemScore(q,x){const hay=arNorm([x.name,x.englishName,x.aliases].filter(Boolean).join(' '));const qt=q.split(' ').filter(w=>w.length>2);let s=0;qt.forEach(w=>{if(hay.includes(w))s+=w.length});if(q.includes(arNorm(x.name)))s+=30;if(x.englishName&&q.includes(arNorm(x.englishName)))s+=30;return s}
  function findItem(q,menu){const ranked=menu.map(x=>[x,itemScore(q,x)]).sort((a,b)=>b[1]-a[1]);if(ranked[0]?.[1]>=4){lastItemId=ranked[0][0].id;return ranked[0][0]}const follow=has(q,['كيف بتنطبخ','كيف بتقدموها','كم سعرها','سعره','مكوناتها','مكوناته','how is it cooked','how is it served','what about it','and it']);if(follow&&lastItemId)return menu.find(x=>x.id===lastItemId)||null;return null}
  function restaurantAnswer(q,st,en){const pairs=[[['متى','دوام','بتفتحو','بتسكروا','hours','open','close'],st.hours,en?'Our opening hours':'ساعات عملنا'],[['وين','عنوان','موقع','location','address'],st.address,en?'Our address':'عنواننا'],[['هاتف','رقم','phone','contact'],st.phone,en?'Phone':'رقم الهاتف'],[['دفع','فيزا','كاش','card','payment'],st.payment,en?'Payment methods':'طرق الدفع'],[['واي فاي','wifi'],st.wifi,en?'Wi‑Fi':'الـ Wi‑Fi'],[['حجز','reservation','book'],st.reservations,en?'Reservations':'الحجوزات'],[['توصيل','سفري','delivery','takeaway'],st.delivery,en?'Delivery / takeaway':'التوصيل والسفري'],[['مواقف','parking'],st.parking,en?'Parking':'المواقف'],[['حلال','halal'],st.halal,en?'Halal':'الحلال']];for(const [keys,val,label] of pairs)if(has(q,keys))return val?`${label}: ${val}`:(en?`That information has not been added by the restaurant yet.`:`هاي المعلومة لسه مش مضافة من إدارة المطعم.`);if(has(q,['سياسه','سياسات','policy','policies']))return st.policies||st.knowledgeBase||(en?'No restaurant policy has been added yet.':'لسه ما انضافت سياسة للمطعم.');return ''}
  function response(message,profile={}){const raw=String(message||'').trim();if(!raw)return 'اكتب سؤالك وأنا معك.';const en=isEnglish(raw),q=arNorm(raw),menu=WajbatiStore.getMenu().filter(x=>x.available),st=WajbatiStore.getSettings();
    const ra=restaurantAnswer(q,st,en);if(ra)return ra;
    const cats=[['drinks',['مشروبات','مشرايب','مشاريب','شراب','drinks','beverages']],['desserts',['حلويات','حلو','dessert','desserts','sweets']],['appetizers',['مقبلات','مقبلاتكم','appetizers','starters']],['salads',['سلطات','سلطه','salads','salad']],['main',['وجبات','اطباق','اكل','main dishes','meals']]];for(const [id,keys] of cats)if(has(q,keys)){const xs=menu.filter(x=>x.category===id);return xs.length?(en?`Here are all available ${id==='drinks'?'drinks':id==='desserts'?'desserts':id==='appetizers'?'appetizers':id==='salads'?'salads':'main dishes'}:\n${list(xs,true)}`:`أكيد، هاي كل ${WajbatiStore.categoryName(id)} المتاحة حاليًا:\n${list(xs,false)}`):(en?'There are no available items in that section right now.':'حاليًا ما في أصناف متاحة بهذا القسم.')}
    const item=findItem(q,menu);if(item){const n=en?(item.englishName||item.name):item.name;if(has(q,['مكونات','مكون','ingredients','contains','made of']))return en?`${n} ingredients: ${item.ingredients||'Not specified by the restaurant.'}`:`مكونات ${n}: ${item.ingredients||'المكونات غير مسجلة بالتفصيل.'}`;if(has(q,['طبخ','تحضير','بتنطبخ','بتعملو','cooked','cooking','prepared','prepare']))return en?`${n} cooking/preparation: ${item.cookingMethod||'Not specified.'}`:`طريقة تحضير ${n}: ${item.cookingMethod||'طريقة التحضير غير مسجلة.'}`;if(has(q,['تقديم','بتقدمو','served','serving','presented']))return en?`${n} serving style: ${item.servingStyle||'Not specified.'}`:`طريقة تقديم ${n}: ${item.servingStyle||'طريقة التقديم غير مسجلة.'}`;if(has(q,['طعم','نكهه','taste','flavor']))return en?`${n} taste: ${item.taste||'Not specified.'}`:`طعم ${n}: ${item.taste||'غير مسجل.'}`;if(has(q,['حار','spicy','spice']))return en?`${n} spice level: ${item.spiceLevel||'Not specified.'}`:`درجة الحار في ${n}: ${item.spiceLevel||'غير مسجلة.'}`;if(has(q,['وقت','قديش بتاخد','prep time','how long']))return en?`${n} preparation time: ${item.prepTime||'Not specified.'}`:`وقت تحضير ${n}: ${item.prepTime||'غير مسجل.'}`;if(has(q,['تعديل','بدون','اشيل','اضيف','custom','customize','without']))return en?`${n} customization: ${item.customization||'Ask the staff about the requested change.'}`:`تعديلات ${n}: ${item.customization||'اسأل الموظف عن التعديل المطلوب.'}`;if(has(q,['حساسيه','allergy','allergens']))return en?`${n} listed allergens: ${(item.allergens||[]).join(', ')||'none listed'}`:`الحساسيات المسجلة في ${n}: ${(item.allergens||[]).join('، ')||'لا يوجد مسجل'}`;if(has(q,['سعرات','كالوري','calories','kcal']))return en?`${n}: about ${item.calories} kcal per listed serving.`:`${n}: تقريبًا ${item.calories} سعرة حرارية للحصة المسجلة.`;if(has(q,['بروتين','protein']))return en?`${n}: ${item.protein} g protein.`:`${n}: ${item.protein} غ بروتين.`;if(has(q,['كرب','كربوهيدرات','carbs','carbohydrates']))return en?`${n}: ${item.carbs} g carbs.`:`${n}: ${item.carbs} غ كربوهيدرات.`;if(has(q,['دهون','fat','fats']))return en?`${n}: ${item.fat} g fat.`:`${n}: ${item.fat} غ دهون.`;if(has(q,['سعر','كم','price','cost']))return en?`${n} costs ${WajbatiStore.money(item.price)} JOD.`:`سعر ${n} هو ${WajbatiStore.money(item.price)} د.أ.`;return en?`${n}: ${item.description}\nPrice: ${WajbatiStore.money(item.price)} JOD • ${item.calories} kcal • Protein ${item.protein} g • Carbs ${item.carbs} g.\nYou can also ask me about ingredients, cooking, serving, allergens or customization.`:`${n}: ${item.description}\nالسعر ${WajbatiStore.money(item.price)} د.أ • ${item.calories} سعرة • بروتين ${item.protein}غ • كرب ${item.carbs}غ.\nواسألني كمان عن المكونات، الطبخ، التقديم، الحساسية أو التعديلات.`}
    const budgetMatch=raw.match(/(?:معي|ميزانيتي|under|below|less than)\s*(\d+(?:\.\d+)?)/i);if(budgetMatch){const max=Number(budgetMatch[1]),xs=menu.filter(x=>x.price<=max).sort((a,b)=>b.protein-a.protein);return xs.length?(en?`Options under ${max} JOD:\n${list(xs,true)}`:`خيارات ضمن ${max} د.أ:\n${list(xs,false)}`):(en?'No available item matches that budget.':'ما في صنف متاح ضمن هالميزانية حاليًا.')}
    if(has(q,['كيتو','keto'])){const xs=[...menu].sort((a,b)=>a.carbs-b.carbs).slice(0,5);return en?`The lowest-carb choices currently are:\n${list(xs,true)}\nCheck ingredients and your personal keto limits.`:`أقل الخيارات بالكربوهيدرات حاليًا:\n${list(xs,false)}\nوبنصح تراجع المكونات وحد الكرب المناسب إلك.`}
    if(has(q,['تنشيف','دايت','تخفيف','خساره وزن','cut','diet','weight loss'])){const xs=[...menu].sort((a,b)=>a.calories-b.calories||b.protein-a.protein).slice(0,5);return en?`For a lighter meal, these are good starting points:\n${list(xs,true)}`:`للتنشيف أو وجبة أخف، هاي خيارات جيدة كبداية:\n${list(xs,false)}`}
    if(has(q,['بناء عضل','عضل','بروتين عالي','muscle','high protein'])){const xs=[...menu].sort((a,b)=>b.protein-a.protein).slice(0,5);return en?`Highest-protein options:\n${list(xs,true)}`:`أعلى الخيارات بالبروتين:\n${list(xs,false)}`}
    if(has(q,['شو بتنصح','اقترح','recommend','suggest'])){let xs=[...menu];if(profile.avoid)xs=xs.filter(x=>!(x.allergens||[]).includes(profile.avoid));if(profile.goal==='muscle')xs.sort((a,b)=>b.protein-a.protein);else if(profile.goal==='cut')xs.sort((a,b)=>a.calories-b.calories);else if(profile.goal==='keto')xs.sort((a,b)=>a.carbs-b.carbs);else xs.sort((a,b)=>Math.abs(a.calories-600)-Math.abs(b.calories-600));return xs[0]?(en?`I recommend ${xs[0].englishName||xs[0].name}: ${xs[0].description}`:`بنصحك بـ ${xs[0].name}: ${xs[0].description}`):(en?'No suitable available item found.':'ما لقيت خيار مناسب ومتاح حاليًا.')}
    if(has(q,['مرحبا','اهلا','هاي','hello','hi','hey']))return en?'Hi! Ask me anything about the restaurant, menu, ingredients, cooking, nutrition or your order.':'أهلًا! اسألني أي شيء عن المطعم، المنيو، المكونات، الطبخ، التغذية أو طلبك.';
    return en?'I can answer anything that is recorded about this restaurant: all menu sections, item ingredients, cooking and serving, taste, spice level, prep time, customization, prices, calories/macros, allergens, recommendations, opening hours, location, payment, Wi‑Fi, reservations and more. Try mentioning the item or topic you mean.':'بقدر أجاوبك عن كل المعلومات المسجلة بخصوص المطعم: كل أقسام المنيو، مكونات أي صنف، طريقة الطبخ والتقديم، الطعم والحار ووقت التحضير والتعديلات، الأسعار والسعرات والماكروز والحساسيات، الترشيحات، الدوام والموقع والدفع والواي فاي والحجوزات وغيرها. احكيلي اسم الصنف أو الموضوع اللي بدك إياه.'
  }
  return response
})();
